function createId(){if(crypto.randomUUID)return crypto.randomUUID();const a=crypto.getRandomValues(new Uint8Array(16));a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;return [...a].map((b,i)=>([4,6,8,10].includes(i)?'-':'')+b.toString(16).padStart(2,'0')).join('')}
const $=s=>document.querySelector(s), money=n=>Math.round(n).toLocaleString('ko-KR')+'원';
const dateKey=(d=new Date())=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const today=dateKey(), month=today.slice(0,7);function weekKey(){let d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return dateKey(d)}
let state={view:'home',profile:{age:'',region:'',renting:'',rent:'',fee:'',transport:'',rides:'',mode:'',route:''},diagnosed:false,records:[],ledger:[],rewards:{flag:false,desk:false,bus:false,rug:false},benefits:[],compared:false,reviewed:false,tip:null,statuses:{},excluded:[]};
const categories=['식비','카페·편의점','교통','주거','기타'];const navs=[['home','⌂','전황판'],['armor','♧','생활 정보'],['records','▤','소비 기록'],['profile','♙','내 정보']];
let pose=0,speech='여기가 우리 성이야? 생각보다… 탁 트였네!',toastTimer;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function award(key,pts){if(state.ledger.some(e=>e.key===key))return 0;state.ledger.push({key,pts,date:today});return pts}
function react(t,p=2){speech=t;pose=p;render();const el=$('.main-mascot');el?.classList.add('jump')}
function total(){return state.records.filter(r=>r.date.startsWith(month)).reduce((n,r)=>n+r.amount,0)}
function points(){return state.ledger.reduce((n,e)=>n+e.pts,0)}
function rewardRows(){return [['flag','🚩','이름표와 작은 깃발','첫 고정비 진단'],['desk','📚','기록용 책상','첫 소비 기록'],['bus','🚌','버스 장난감','첫 교통비 비교'],['rug','🟠','포근한 러그','첫 주간 점검']].map(([k,i,t,d])=>`<div class="reward-row ${state.rewards[k]?'unlocked':''}"><span class="reward-icon">${i}</span><div><strong>${t}</strong><small>${d}</small></div><span>${state.rewards[k]?'✓':'○'}</span></div>`).join('')}
function room(){return `<section class="room room-level-${Math.min(3,1+Math.floor(points()/50))}"><div class="room-top"><span class="room-tag">${state.diagnosed?'🚩 텅이의 작은 성':'🌱 우리의 첫 성터'}</span><button onclick="roomInfo()" aria-label="방 꾸미기 안내">?</button></div><div class="bubble" aria-live="polite">${esc(speech)}</div><span class="item flag ${state.rewards.flag?'':'locked'}" title="작은 깃발">🚩</span><span class="item desk ${state.rewards.desk?'':'locked'}" title="기록용 책상">🪑<span style="font-size:25px">📚</span></span><span class="item bus ${state.rewards.bus?'':'locked'}" title="버스 장난감">🚌</span>${state.rewards.rug?'<span class="item rug" title="포근한 러그">🟠</span>':''}<button class="mascot main-mascot" data-pose="${pose}" onclick="pet()" aria-label="텅이와 놀기"></button><span class="room-title">${points()>=100?'함께 지켜낸 든든한 공간':points()>=50?'조금씩 포근해지는 우리 집':'작지만, 우리만의 든든한 시작'}</span></section><span class="room-hint">텅이를 톡 눌러보세요. 오늘은 무슨 생각을 하고 있을까요?</span>`}
function navigate(v){state.view=v;render()}
function render(){const p=points();$('#nav').innerHTML=navs.map(([k,i,t])=>`<button onclick="navigate('${k}')" class="${state.view===k?'active':''}"><i>${i}</i>${t}</button>`).join('');$('#title').textContent={home:'반가워요, 수호대원!',armor:'나에게 맞는 생활 정보',records:'작은 기록, 든든한 하루',profile:'우리의 작전을 세워볼까요?'}[state.view];$('#subtitle').textContent={home:'잘 아끼는 날도, 잘 기록하는 날도. 모두 성장하는 날이에요.',armor:'조건을 읽고, 비교하고, 내 생활에 맞게 선택해요.',records:'꼭 필요한 소비도, 나를 위한 소비도 편하게 기록해요.',profile:'아는 만큼만 알려주세요. 모르는 항목은 비워도 괜찮아요.'}[state.view];$('#today').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date());$('#level').textContent=p>=100?'Lv. 3 든든한 우리 집':p>=50?'Lv. 2 포근한 보금자리':'Lv. 1 작은 시작';$('#points').textContent=p+' GP';$('#next').textContent=p>=100?'최고 데모 단계 달성':`다음 성장까지 ${50-p%50} GP`;$('#bar').style.width=(p>=100?100:p%50*2)+'%';$('#weekPoints').textContent=state.ledger.filter(e=>e.date>=weekKey()).reduce((s,e)=>s+e.pts,0)+' GP';$('#reward-count').textContent=Object.values(state.rewards).filter(Boolean).length+' / 4';$('#rewards').innerHTML=rewardRows();$('#content').innerHTML=({home:home,armor:armor,records:records,profile:profile})[state.view]()}
function home(){return `${!state.diagnosed?'<div class="setup-banner"><div><strong>텅이와 첫 작전을 시작해요</strong><p>고정비를 등록하면 작은 깃발과 30 GP를 받아요.</p></div><button class="primary" onclick="navigate(\'profile\')">첫 진단하기 →</button></div>':''}${room()}<div class="metrics"><div class="card metric"><span>이번 달 실제 지출</span><strong>${money(total())}</strong><small>${state.records.some(r=>r.sample)?'샘플 기록 포함':'직접 기록한 지출'}</small></div><div class="card metric"><span>예상 절약액</span><strong>아직 없음</strong><small>검증된 금액만 표시해요</small></div><div class="card metric"><span>확인한 혜택</span><strong>${state.benefits.length?money(state.benefits.reduce((a,b)=>a+b.amount,0)):'아직 없음'}</strong><small>사용자 입력 기준 · 누적</small></div></div><div class="section-heading"><h2>오늘의 작은 한 걸음</h2><small>부담 없이, 하나씩</small></div><div class="action-grid"><section class="card action-card"><div class="icon-tile">▤</div><span class="tag">하루 1회 +5 GP</span><h3>오늘 쓴 돈, 가볍게 기록</h3><p>기억보다 기록이 든든하니까.</p><button onclick="recordModal()">소비 기록하기 ＋</button></section><section class="card action-card"><div class="icon-tile">⇄</div><span class="tag">월 1회 +10 GP</span><h3>교통비 생활 정보 찾기</h3><p>내 이동 습관에 맞는 선택지를 비교해요.</p><button onclick="compareModal()">교통비 비교하기 →</button></section></div><section class="weekly"><div class="icon-tile">⌕</div><div><h3>이번 주 생활 점검</h3><p>반복된 소비를 살펴보고, 한 가지만 실천해요.</p></div><button class="primary" onclick="reviewModal()">${state.reviewed?'점검 다시 보기':'텅이와 점검하기'}</button></section><div class="section-heading"><small>기록이 없다면 샘플로 먼저 체험해보세요.</small><button onclick="loadSample()" style="font-size:11px;color:var(--green)">7일 샘플 불러오기 ↗</button></div>`}
function field(label,name,type='number',placeholder='건너뛰기 가능'){return `<label class="field">${label}<input name="${name}" type="${type}" ${type==='number'?'min="0" max="100000000"':''} value="${esc(state.profile[name])}" placeholder="${placeholder}"></label>`}
function select(label,name,opts){return `<label class="field">${label}<select name="${name}"><option value="">모르겠어요 / 건너뛰기</option>${opts.map(o=>`<option ${state.profile[name]===o?'selected':''}>${o}</option>`).join('')}</select></label>`}
function profile(){return `<form class="card full-card" onsubmit="saveProfile(event)"><h2>기본 정보와 고정비</h2><p>예상 금액을 입력해도 괜찮아요. 실제 지출 기록에는 더해지지 않아요.</p><div class="fields">${field('만 나이','age')}${select('거주 지역','region',['서울','경기','인천','그 외 지역'])}${select('월세 거주 여부','renting',['월세 거주','월세 아님'])}${field('월세 (원)','rent')}${field('월 관리비 (원)','fee')}${field('월 예상 교통비 (원)','transport')}${field('월 교통 이용 횟수','rides')}${select('주요 교통수단','mode',['버스·지하철','광역버스·GTX','택시·자가용'])}${select('주요 이용 구간','route',['서울 내 이동','서울·경기·인천 이동','그 외 구간'])}</div><div class="notice">서울 거주자의 주거 정책 후보와 교통 비교 흐름을 체험할 수 있어요. 자격 판단과 실제 지급액 확정은 하지 않아요.</div><div class="form-actions"><button type="button" class="secondary" onclick="fillProfile()">예시 정보 채우기</button><button class="primary" type="submit">${state.diagnosed?'정보 수정하고 다시 진단':'첫 진단 완료 · +30 GP'}</button></div></form>${state.diagnosed?'<section class="card full-card"><h2>첫 진단 결과</h2><p>교통비는 입력 조건으로 비교해 보고, 주거 지원은 추가 조건을 확인해요.</p><div class="table-actions"><button class="primary" onclick="compareModal()">교통비 비교하기</button><button class="secondary" onclick="navigate(\'armor\')">지원 조건 확인하기</button></div></section>':''}`}
function fillProfile(){const f=$('#content form');Object.entries({age:24,region:'서울',renting:'월세 거주',rent:550000,fee:50000,transport:80000,rides:40,mode:'버스·지하철',route:'서울 내 이동'}).forEach(([k,v])=>f.elements[k].value=v);toast('예시 정보예요. 원하는 값으로 바꿔보세요.')}
function saveProfile(e){e.preventDefault();state.profile=Object.fromEntries(new FormData(e.target));state.diagnosed=true;state.rewards.flag=true;const n=award('diagnosis',30);pose=2;speech='우리 성에 이름표가 생겼어! 이제 작전을 세워볼까?';render();toast(n?'첫 진단 완료! 작은 깃발과 +30 GP':'고정비 정보를 수정했어요. 비교 결과도 다시 확인해요.')}
function recordModal(id){const r=state.records.find(r=>r.id===id);modal(`<h2>${r?'소비 기록 수정':'오늘의 소비 기록'}</h2><p>잘 썼는지 판단하지 않아요. 남겨두는 것만으로 충분해요.</p><form onsubmit="saveRecord(event,${id?`'${id}'`:'null'})"><div class="fields"><label class="field">금액 (원)<input name="amount" type="number" min="1" max="100000000" step="1" required value="${r?.amount??''}" placeholder="예: 6500"></label><label class="field">카테고리<select name="category">${categories.map(c=>`<option ${r?.category===c?'selected':''}>${c}</option>`).join('')}</select></label><label class="field wide">날짜<input name="date" type="date" required max="${today}" value="${r?.date??today}"></label></div><label class="check"><input name="oneOff" type="checkbox" ${r?.oneOff?'checked':''}>이번 한 번만 발생한 지출</label><div class="form-actions"><button class="primary" type="submit">${r?'수정 완료':'기록 완료'}</button></div></form>`)}
function saveRecord(e,id){e.preventDefault();const f=new FormData(e.target),amount=Number(f.get('amount')),date=f.get('date'),category=f.get('category');if(!Number.isFinite(amount)||amount<=0||amount>1e8||!categories.includes(category)||!/^\d{4}-\d{2}-\d{2}$/.test(date)||date>today)return toast('금액과 날짜를 확인해주세요.');let n=0;const item={id:id||createId(),amount,date,category,oneOff:f.has('oneOff')};if(id){const i=state.records.findIndex(r=>r.id===id);item.sample=state.records[i].sample;state.records[i]=item}else{state.records.push(item);n=award('record-'+today,5);state.rewards.desk=true}closeModal();react('접수 완료! 기억보다 기록이 든든하지.');toast(id?'기록을 수정했어요.':`기록 완료! ${n?'+5 GP · 기록용 책상 획득':'오늘의 기록 포인트는 이미 받았어요'}`)}
function records(){const rs=[...state.records].sort((a,b)=>b.date.localeCompare(a.date));return `<section class="card full-card"><div class="policy-top"><div><h2>소비 기록</h2><p>이번 달 ${money(total())} · ${state.records.filter(r=>r.date.startsWith(month)).length}건</p></div><button class="primary" onclick="recordModal()">＋ 기록하기</button></div><div class="table-actions"><button class="secondary" onclick="loadSample()">7일 샘플 불러오기</button>${state.records.some(r=>r.sample)?'<button class="secondary" onclick="removeSamples()">샘플 기록 지우기</button>':''}</div>${rs.length?rs.map(r=>`<div class="row"><div><b>${esc(r.category)}</b><small>${r.date}${r.sample?' · 샘플':''}${r.oneOff?' · 일회성':''}</small></div><strong>${money(r.amount)}</strong><div><button onclick="recordModal('${r.id}')">수정</button><button onclick="deleteRecord('${r.id}')">삭제</button></div></div>`).join(''):'<div class="empty">아직 기록이 없어요.<br>작은 소비 하나부터 남겨볼까요?</div>'}</section>`}
function deleteRecord(id){modal(`<h2>이 기록을 삭제할까요?</h2><p>실제 지출 합계와 주간 분석에 반영돼요. 이미 받은 성장 포인트는 유지돼요.</p><div class="form-actions"><button class="secondary" onclick="closeModal()">취소</button><button class="primary" onclick="confirmDelete('${id}')">삭제하기</button></div>`)}
function confirmDelete(id){state.records=state.records.filter(r=>r.id!==id);closeModal();render();toast('기록을 삭제했어요.')}
function loadSample(){if(state.records.some(r=>r.sample))return toast('샘플은 이미 불러왔어요. 소비 기록에서 확인해요.');for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-i);state.records.push({id:createId(),amount:[8200,7600,11400,9000,6300,8700,5800][i],category:'카페·편의점',date:dateKey(d),oneOff:false,sample:true})}state.records.push({id:createId(),amount:72000,category:'기타',date:today,oneOff:true,sample:true});state.excluded=[];render();toast('샘플 8건을 불러왔어요. 포인트는 지급되지 않아요.')}
function removeSamples(){state.records=state.records.filter(r=>!r.sample);render();toast('샘플 기록을 모두 지웠어요.')}
function compareModal(){modal(`<h2>교통비 생활 정보 비교</h2><p>숫자를 바꿔보며 비교 흐름을 체험해요.</p><form oninput="updateComparison()" onsubmit="finishCompare(event)"><div class="fields"><label class="field">월 예상 교통비 (원)<input name="cost" id="cost" type="number" min="0" max="10000000" required value="${esc(state.profile.transport||80000)}"></label><label class="field">월 이용 횟수<input name="rides" id="rides" type="number" min="0" max="1000" required value="${esc(state.profile.rides||40)}"></label><label class="field wide">이번 비교에 쓸 가정<select id="plan"><option value="rate">가상 환급형 · 15회 이상, 30% 환급</option><option value="pass">가상 정액형 · 월 55,000원</option></select></label></div><div id="comparison"></div><div class="notice">데모 계산 전용 가정이에요. 실제 K-패스·기후동행카드의 2026년 전체 제도나 개인 자격을 반영한 견적이 아니며, 예상 절약액 합계에 포함되지 않아요. 기본 예시: 80,000원 / 40회.</div><div class="form-actions"><button class="primary" type="submit">비교 완료 · 버스 장난감 받기</button></div></form>`);updateComparison()}
function calculate(cost,rides,plan){if(!Number.isFinite(cost)||cost<0||!Number.isFinite(rides)||rides<0)return null;const after=plan==='rate'?(rides>=15?Math.round(cost*.7):cost):55000;return {cost,after,difference:cost-after}}
function updateComparison(){const x=calculate(Number($('#cost').value),Number($('#rides').value),$('#plan').value);$('#comparison').innerHTML=x?`<div class="comparison"><div>현재 예상 비용<strong>${money(x.cost)}</strong></div><div>가정 적용 후<strong>${money(x.after)}</strong></div></div><div class="legend">${x.difference>=0?'월 비용 차이 '+money(x.difference):'현재 방식이 '+money(-x.difference)+' 더 저렴해요.'}<br>${$('#plan').value==='rate'?'계산: 월 교통비 × (1 − 30%). 15회 미만이면 환급 없음.':'계산: 월 교통비 − 가상 정액권 55,000원.'} 대체 혜택은 합산하지 않아요.</div>`:'금액과 횟수를 확인해주세요.'}
function finishCompare(e){e.preventDefault();if(!calculate(Number($('#cost').value),Number($('#rides').value),$('#plan').value))return;state.rewards.bus=true;state.compared=true;const n=award('compare-transport-'+month,10);closeModal();react('모양 말고 조건으로 골라야겠어. 버스는 내가 맡을게!');toast(`교통비 비교 완료! ${n?'+10 GP · 버스 장난감 획득':'이번 달 비교 포인트는 이미 받았어요'}`)}
const policies=[{id:'kpass',title:'K-패스',icon:'🚌',type:'교통 · 전국 참여 지역',desc:'이용 횟수와 연령, 거주 지역에 따라 환급 조건을 확인해요. 기본형과 추가 제도까지 공식 안내에서 비교하세요.',url:'https://main.kotsa.or.kr/portal/contents.do?menuCode=01080300',source:'한국교통안전공단',conditions:'참여 지자체 주민등록, 회원가입, 대상 교통수단, 월 이용 횟수, 연령·우대 유형, 실제 적용 제도를 확인해야 해요.'},{id:'seoul-rent',title:'서울시 청년월세지원',icon:'🏡',type:'주거 · 서울',desc:'서울에 사는 월세 청년이라면 살펴볼 지원 후보예요. 지금 신청 가능한지는 해당 연도 공고를 확인해주세요.',url:'https://housing.seoul.go.kr/site/main/content/sh01_060513',source:'서울주거포털',conditions:'연령, 서울 주민등록·실거주, 보증금·월세, 소득·가구, 재산, 중복 수혜, 접수 기간을 추가 확인해야 해요. 선정이나 수령을 보장하지 않아요.'},{id:'moving',title:'청년 주거 지원 정책 모아보기',icon:'📦',type:'주거 · 서울 공식 탐색',desc:'이사비·중개보수와 임차보증금 등 다른 주거 지원을 공식 정책 목록에서 살펴봐요.',url:'https://youth.seoul.go.kr/mainB.do',source:'청년몽땅정보통',conditions:'개별 사업의 연령·거주·이사 시점·소득·중복 지원과 모집 여부가 달라요. 이 항목은 확정된 추천이 아닌 공식 정책 탐색 링크예요.'}];
function armor(){return `<div class="notice">공식 안내 확인일: 2026.09.12 · 주거는 서울을 지원 범위로 해요. 모든 정책은 자격 미확인 후보이며 금액 합계에 넣지 않아요.</div><div class="table-actions" style="margin-bottom:18px"><button class="primary" onclick="compareModal()">교통비 비교 체험</button><button class="secondary" onclick="benefitModal()">실제 받은 혜택 등록</button></div>${policies.map(p=>`<section class="card full-card"><div class="policy-top"><div><span class="tag">${p.type}</span><h2 style="margin-top:13px">${p.icon} ${p.title}</h2></div><span class="tag">${p.id!=='kpass'&&state.profile.region&&state.profile.region!=='서울'?'지원 범위 밖':'자격 확인 필요'}</span></div><p>${p.desc}</p><div class="policy-actions"><button class="secondary" onclick="policyModal('${p.id}')">조건 확인하기</button><a target="_blank" rel="noopener" href="${p.url}">${p.source} ↗</a><label style="margin-left:auto;font-size:12px">실행 상태 <select onchange="state.statuses['${p.id}']=this.value"><option>확인 전</option>${['확인 중','신청 준비','신청 완료'].map(s=>`<option ${state.statuses[p.id]===s?'selected':''}>${s}</option>`).join('')}</select></label></div></section>`).join('')}${state.tip?`<section class="card full-card"><span class="tag">주간 점검에서 발견</span><h2 style="margin-top:13px">이번 주 한 가지 실천</h2><p>${state.tip}</p><small>일반적인 소비 팁 · 절약 금액은 추정하지 않아요.</small></section>`:''}`}
function policyModal(id){const p=policies.find(p=>p.id===id);modal(`<h2>${p.title}</h2><p>${p.conditions}</p><div class="notice">${p.id==='seoul-rent'?'서울 2026 공고의 기본 연령 범위는 19~39세이며 군 복무 등에 따른 예외가 있어요. 소득·가구·재산 조건을 종합적으로 확인해야 해요.':'공식 안내에서 상세 조건과 현재 모집 여부를 확인해요.'}</div>${id==='seoul-rent'?'<label class="field">소득·가구 조건 확인 여부<select><option>아직 모르겠어요</option><option>공식 안내에서 확인 중이에요</option><option>필요한 서류를 준비했어요</option></select></label>':''}<p>지원금은 실제 수령 후에만 별도로 등록해요. 신청 상태를 바꿔도 혜택 금액은 늘어나지 않아요.</p><div class="form-actions"><a class="primary" style="text-decoration:none" target="_blank" rel="noopener" href="${p.url}">공식 안내 확인 ↗</a></div>`)}
function benefitModal(){modal(`<h2>실제 받은 혜택 등록</h2><p>실제로 입금된 환급·지원금만 입력해주세요. 사용자 입력 기준으로 표시해요.</p><form onsubmit="saveBenefit(event)"><div class="fields"><label class="field">받은 혜택 금액 (원)<input name="amount" type="number" min="1" max="100000000" required></label><label class="field">수령 날짜<input type="date" name="date" max="${today}" value="${today}" required></label></div><label class="check"><input type="checkbox" required>실제 수령한 금액임을 확인했어요.</label><div class="form-actions"><button class="primary">등록하기</button></div></form>${state.benefits.map((b,i)=>`<div class="row"><span>${b.date} · ${money(b.amount)}</span><button onclick="state.benefits.splice(${i},1);render();benefitModal()">등록 취소</button></div>`).join('')}`)}
function saveBenefit(e){e.preventDefault();const f=new FormData(e.target);state.benefits.push({amount:Number(f.get('amount')),date:f.get('date')});closeModal();render();toast('확인한 혜택에 등록했어요. 성장 포인트와는 별개예요.')}
function candidates(records=state.records){const d=new Date();d.setDate(d.getDate()-6);const start=dateKey(d);return categories.map(category=>{const rows=records.filter(r=>r.category===category&&!r.oneOff&&r.date>=start&&r.date<=today);return {category,days:new Set(rows.map(r=>r.date)).size,sum:rows.reduce((n,r)=>n+r.amount,0),sample:rows.some(r=>r.sample)}}).filter(c=>c.days>=3&&!state.excluded.includes(c.category)).sort((a,b)=>b.sum-a.sum)}
function reviewModal(){if(state.reviewed){modal(`<h2>이번 주도 한 블록 더!</h2><div class="mascot modal-mascot" style="background-position:0 100%"></div><p>${state.tip||'이번 주에만 생긴 소비는 점검에서 제외했어요. 다음 주에 다시 살펴봐요.'}</p><div class="notice">이번 주 점검 포인트는 이미 받았어요. 기록은 계속 수정하거나 추가할 수 있어요.</div><button class="primary" onclick="closeModal()">좋아, 한 걸음씩</button>`);return}const c=candidates()[0];if(!c){pose=1;speech='아직 단서가 부족해. 괜히 아는 척은 안 할게.';render();modal(`<h2>아직 단서가 조금 부족해요</h2><div class="mascot modal-mascot" style="background-position:100% 0"></div><p>최근 7일 중 서로 다른 3일 이상 기록된 카테고리를 찾아요. 일회성 지출과 이번 점검에서 제외한 항목은 빼고 살펴봤어요.</p><div class="notice">분석은 보류할게요. 고정비 진단은 지금도 이용할 수 있어요. 이번 점검 포인트는 아직 지급되지 않아요.</div><div class="form-actions"><button class="secondary" onclick="closeModal();loadSample();reviewModal()">샘플로 체험</button><button class="primary" onclick="closeModal();navigate('armor')">고정비 살펴보기</button></div>`);return}modal(`<span class="tag">최근 7일 ${c.sample?'· 샘플 포함':''}</span><h2 style="margin-top:14px">평소에도 비슷한가요?</h2><p>${c.category} 지출이 여러 날 반복됐어요. 낭비라는 뜻은 아니에요. 평소의 소비인지 먼저 알려주세요.</p><div class="review-stats"><span>${c.days}일에 걸친 기록</span><strong>${money(c.sum)}</strong></div><div class="legend">반복 후보 중 합계가 가장 큰 항목 한 가지만 보여드려요.</div><div class="form-actions"><button class="secondary" onclick="excludeReview('${c.category}')">이번 주만 그래요</button><button class="primary" onclick="reviewTip('${c.category}')">평소에도 그래요</button></div>`)}
function excludeReview(c){state.excluded.push(c);state.tip=null;modal('<h2>이번 주만의 소비였군요!</h2><p>이 항목은 이번 점검에서 제외할게요. 소비의 이유는 내가 가장 잘 아니까요.</p><div class="form-actions"><button class="primary" onclick="finishReview()">점검 완료 · +20 GP</button></div>')}
function reviewTip(c){const tips={'카페·편의점':'이번 주는 카페·편의점에 들르기 전에 필요한 것을 하나만 정해보세요. 다음 점검 때 나에게 편한 방법이었는지 돌아봐요.','식비':'이번 주 한 끼만 미리 메뉴를 정해보세요. 무리한 제한 없이 계획이 도움이 되는지 살펴봐요.','교통':'자주 이동하는 구간 하나를 골라 교통비 생활 정보의 적용 범위를 확인해보세요. 필요한 이동을 줄일 필요는 없어요.','주거':'월세와 관리비가 각각 어떻게 기록되어 있는지 한 번 확인해보세요. 주거 지원 후보의 조건도 함께 살펴봐요.','기타':'기타 지출 가운데 자주 생기는 한 항목을 다음 기록 때 구분해서 살펴보세요. 카테고리만으로 구매한 물건을 추측하지는 않을게요.'};state.tip=tips[c];modal(`<h2>이번 주는, 딱 한 가지만</h2><div class="mascot modal-mascot" style="background-position:0 100%"></div><p>${state.tip}</p><div class="notice">반복 패턴을 함께 확인한 뒤 제안하는 일반적인 방법이에요. 절약 금액은 추정하지 않아요.</div><div class="form-actions"><button class="primary" onclick="finishReview()">점검 완료 · 스탠드 받기</button></div>`)}
function finishReview(){state.reviewed=true;state.rewards.rug=true;const n=award('review-'+weekKey(),20);closeModal();react('이번 주도 한 블록 더! 이제 러그에서 좀 쉬어도 되지?');toast(`주간 점검 완료! ${n?'+20 GP · 포근한 스탠드 획득':'이번 주 포인트는 이미 받았어요'}`)}
function pet(){const lines=[['방패가 좀 크지? 그래도 의욕은 더 크다고!',0],['월세 드래곤은… 일단 작전부터 세우자.',1],['왔구나! 네 자리 비워뒀어.',2],['잠깐 쉬는 것도 작전의 일부야… 쿨.',3],['오늘은 기록했으니까 됐어. 나머지는 내일의 우리에게!',0]];const l=lines[Math.floor(Math.random()*lines.length)];speech=l[0];pose=l[1];render()}
function roomInfo(){modal(`<h2>행동이 쌓이는 텅이의 방</h2><p>정해진 행동을 처음 완료하면 소품이 생겨요. 캐릭터를 눌러도 포인트는 늘지 않아요.</p>${rewardRows()}<div class="notice">진단 30 GP · 최초 1회<br>기록 5 GP · 하루 1회<br>교통 비교 10 GP · 같은 항목 월 1회<br>주간 점검 20 GP · 주 1회<br>50 GP와 100 GP에 공간 단계가 올라가요.</div>`)}
function modal(html){$('#modal-body').innerHTML=`<div class="modal-head"><span class="eyebrow">TEONG DEFENSE</span><button class="close" onclick="closeModal()" aria-label="닫기">×</button></div>${html}`;if(!$('#modal').open)$('#modal').showModal()}
function closeModal(){$('#modal').close()}
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
$('.brand').onclick=e=>{e.preventDefault();navigate('home')};
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_teong_dashboard',description:'Read the current demo expenses, growth points and room rewards without modifying them.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input&&Object.keys(input).length)throw new Error('No input fields accepted');return {actualExpenses:total(),growthPoints:points(),roomRewards:{...state.rewards},recordCount:state.records.length,demo:true}}})).catch(()=>{})}catch{}}

const baseArmorView=armor;
