/* Full-stack integration. API keys and passwords never enter saved client state. */
const roomHome=home, v2render=render, v2profile=profile;
const initialState=JSON.parse(JSON.stringify(state));
let accountUser=null,revision=0,guest=false,ready=false,lastSaved='',saveTimer,saveTask=null,saveError='',tabMode='diagnosis',calc=null,calcResult=null;
const snapshot=()=>JSON.stringify(state, (k,v)=>['view','gameRound','interaction','mementos','decor'].includes(k)?undefined:v);
async function api(path,body,method='POST'){const r=await fetch('/api/'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},...(body!==undefined?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'요청을 완료하지 못했어요.');return d}
function syncLabel(t){const e=$('#sync-status');if(e)e.textContent=t}
async function flush(){clearTimeout(saveTimer);if(guest||!accountUser)return;if(saveTask){await saveTask;if(snapshot()!==lastSaved)return flush();return}const payload=snapshot();if(payload===lastSaved)return;syncLabel('저장 중…');saveTask=(async()=>{try{const d=await api('account',{state:JSON.parse(payload),revision},'PUT');revision=d.revision;lastSaved=payload;calcResult=d.diagnosis;saveError='';syncLabel('서버에 저장됨')}catch(e){saveError=e.message;syncLabel('저장 실패 · 눌러서 재시도');throw e}finally{saveTask=null}})();return saveTask}
function queueSave(){if(!ready||guest||!accountUser||snapshot()===lastSaved)return;syncLabel('저장 대기');clearTimeout(saveTimer);saveTimer=setTimeout(()=>flush().catch(()=>{}),400)}
function evoStyle(level){return `background-image:url('evolution.png');background-size:200% 200%;background-position:${state.character==='tang'?'0':'100%'} ${level===2?'0':'100%'};`}
render=function(){if(state.reviewWeek!==weekKey()){state.reviewWeek=weekKey();state.reviewed=state.ledger.some(x=>x.key==='review-'+weekKey());state.excluded=[]}v2render();const lv=Math.min(3,1+Math.floor(points()/50));if(lv>1)document.querySelectorAll('.main-mascot,.companion-profile .portrait').forEach(e=>{e.style.cssText+=evoStyle(lv);e.classList.add('evolved')});$('#nav').innerHTML=`<button class="${state.view==='home'&&tabMode==='diagnosis'?'active':''}" onclick="go('diagnosis')"><i>⌂</i>주거·교통 진단</button><button class="${state.view==='home'&&tabMode==='room'?'active':''}" onclick="go('room')"><i>✿</i>우리 집 꾸미기</button><button onclick="navigate('records')"><i>▤</i>소비 기록</button><button onclick="navigate('profile')"><i>♙</i>내 정보</button>`;if(state.view==='home'){$('#title').textContent=tabMode==='room'?'우리가 함께 키우는 집':'사는 곳과 다니는 길, 함께 가볍게.';$('#subtitle').textContent=tabMode==='room'?'생활을 점검할수록 방과 동료가 자라요.':'탕이·텅이와 내 조건을 알아보고, 받을 수 있는 혜택을 계산해요.'}$('.demo-pill').innerHTML=`<button id="sync-status" onclick="flush().catch(e=>toast(e.message))">${guest?'샘플 체험 · 저장 안 됨':saveError?'저장 실패 · 재시도':accountUser?'서버에 저장됨':'로그인 필요'}</button>`;$('footer').textContent='2026.09.12 확인 · 서울 청년 / 2026년 9월 교통 계산 범위 · 기관 심사와 실제 환급액은 다를 수 있어요.';$('.profile').innerHTML=`<div class="avatar">나</div><div>${esc(accountUser?state.profile.nickname||'수호대원':'체험 중')}<small>${accountUser?'회원별 데이터 저장':'샘플 · 새로고침 시 초기화'}</small></div><button onclick="signOut()">${accountUser?'로그아웃':'로그인'}</button>`;$('.growth').insertAdjacentHTML('beforeend','<button class="secondary" onclick="evolutionPreview()">진화 모습 보기 ↗</button>');queueSave()};
home=function(){if(tabMode==='room')return roomHome().replace('<b>아직 없음</b>','<b>'+(calc?.diagnose(state).estimatedMonthly!=null?money(calc.diagnose(state).estimatedMonthly):'아직 없음')+'</b>');const d=calc?calc.diagnose(state):null;return `<section class="diagnosis-hero"><div><span class="eyebrow">HOME & MOBILITY COMPANION</span><h2>월세도, 매일 가는 길도.<br>혼자 알아보지 않아도 돼.</h2><p>네 생활을 알려주면 내가 조건을 정리해줄게.<br>계산은 정확하게, 설명은 우리답게!</p><button class="primary" onclick="openGuide('transport')">${who().name}와 혜택 이야기하기 ↗</button></div><div class="hero-character mascot" style="background-image:url('${who().file}')"></div></section><div class="mission-grid"><button class="mission-card housing" onclick="openGuide('housing')"><span class="mission-category">01 / 주거비 진단</span><strong>내 월세, 지원받을 수 있을까?</strong><p>${d?.housing.conditionalMonthly!=null?'선정 가정 월 '+money(d.housing.conditionalMonthly):'소득·보증금·가구 조건부터 함께 확인해요.'}</p><span class="mission-reward">2026 접수 종료 · 조건부 금액 별도 표시 →</span></button><button class="mission-card commute" onclick="openGuide('transport')"><span class="mission-category">02 / 교통비 진단</span><strong>같은 길, 더 가벼운 교통비</strong><p>${d?.estimatedMonthly!=null?'예상 월 환급 '+money(d.estimatedMonthly):'금액과 이용 조건으로 예상 환급액을 계산해요.'}</p><span class="mission-reward">K-패스 · 모두의 카드 비교 →</span></button></div><div class="compact-summary"><div><small>기록한 실제 지출 · 이번 달</small><b>${money(total())}</b></div><div><small>예상 월 절약 · 교통만</small><b>${d?.estimatedMonthly!=null?money(d.estimatedMonthly):'아직 없음'}</b></div><div><small>확인한 혜택 · 사용자 입력</small><b>${state.benefits.length?money(state.benefits.reduce((n,b)=>n+b.amount,0)):'아직 없음'}</b></div></div><section class="card next-home"><div><span class="eyebrow">A LITTLE BETTER, TOGETHER</span><h2>생활의 발견이, 우리 집의 변화로.</h2><p>진단하고 기록한 경험으로 동료가 진화하고 가구가 생겨요.</p></div><button class="primary" onclick="go('room')">우리 집 꾸미기 →</button></section><div class="companion-controls"><button onclick="recordModal()">＋ 소비 기록하기</button><button onclick="reviewModal()">이번 주 방어 점검</button><button onclick="benefitModal()">받은 혜택 등록</button></div><p class="legend">주거 지원금은 자격·선정 미확인 및 접수 종료로 예상 절약액에 합산하지 않아요. GP는 돈과 별개예요.</p>`};
function go(t){tabMode=t;state.view='home';render()}
armor=function(){return home()};
profile=function(){return v2profile()+`<section class="card full-card"><h2>내 계정</h2><p>${esc(accountUser?.email||'저장되지 않는 샘플 체험')}</p><button class="secondary" onclick="signOut()">로그아웃 / 로그인</button> <button class="secondary" onclick="removeAccount()">계정 및 저장 데이터 삭제</button></section>`};
function evolutionPreview(){modal(`<h2>${who().name}의 세 가지 성장</h2><p>GP는 사용해도 없어지는 화폐가 아니라 함께한 경험이에요. 50 GP와 100 GP에서 모습이 바뀌어요.</p><div class="evo-line"><div><span class="mascot" style="background-image:url('${who().file}')"></span><b>1단계 · 신입 수호자</b><small>0 GP · 작은 망토</small></div>${[2,3].map(l=>`<div><span class="mascot evolved" style="${evoStyle(l)}"></span><b>${l}단계 · ${l===2?'생활 탐험가':'든든한 수호자'}</b><small>${(l-1)*50} GP · ${l===2?'조끼와 가방':'월계관과 긴 망토'}</small></div>`).join('')}</div><p>미리보기에는 포인트가 지급되지 않아요. 성별에 따른 능력 차이는 없어요.</p>`)}
function field(label,name,value='',type='number'){return `<label class="field">${label}<input name="${name}" type="${type}" ${type==='number'?'min="0"':''} value="${esc(value)}"></label>`}
function selectField(label,name,options,value){return `<label class="field">${label}<select name="${name}"><option value="">아직 모르겠어요</option>${options.map(([v,t])=>`<option value="${v}" ${value===v?'selected':''}>${t}</option>`).join('')}</select></label>`}
const yesNo=[['yes','예 · 조건 확인함'],['no','아니요']];
function openGuide(topic){const p=state.profile,a=state[topic+'Answers']||{};modal(`<span class="tag">${topic==='housing'?'주거':'교통'} 상담 · 계산 + 동료의 설명</span><div class="guide-intro"><span class="mascot portrait" style="background-image:url('${who().file}')"></span><div><h2>${who().name}와 같이 알아보자.</h2><p>${topic==='housing'?'월세는 관리비와 따로 볼게. 모르는 조건은 비워도 괜찮아.':'네가 매일 가는 길부터 알려줘. 숫자를 바꾸면 결과도 달라져!'}</p></div></div><form id="guide-form" onsubmit="runGuide(event,'${topic}')"><div class="fields">${field('만 나이','p_age',p.age)}${selectField('거주 지역','p_region',[['서울','서울'],['경기','경기'],['인천','인천'],['그 외 지역','그 외 지역']],p.region)}${topic==='transport'?`${field('월 교통비 (원)','p_transport',p.transport)}${field('월 이용 횟수','p_rides',p.rides)}${selectField('주요 교통수단','p_mode',[['버스·지하철','버스·지하철'],['광역버스·GTX','광역버스·GTX'],['택시·자가용','택시·자가용']],p.mode)}${selectField('카드·K-패스 회원 등록 완료','registered',yesNo,a.registered)}${selectField('모든 이용일에 하루 2회 이내','daily',yesNo,a.daily)}${selectField('1회 운임 (환승 합산)','fare',[['low','모두 3,000원 미만'],['high','3,000원 이상 포함']],a.fare)}${field('시차 시간대에 쓴 교통비 (원)','offpeak',a.offpeak)}`:`${selectField('월세 거주 여부','p_renting',[['월세 거주','월세 거주'],['월세 아님','월세 아님']],p.renting)}${field('월세 (관리비 제외, 원)','p_rent',p.rent)}${field('출생연도','birthYear',a.birthYear)}${field('임차 보증금 (원)','deposit',a.deposit)}${field('건강보험 기준 가구원 수 (1~6)','household',a.household)}${field('건강보험 가구 기준 월 소득 (원)','income',a.income)}${field('일반재산 가액 (원)','assets',a.assets)}${field('자동차 시가표준액 (없으면 0)','car',a.car)}${selectField('본인 무주택 여부','noHome',yesNo,a.noHome)}${selectField('서울 주민등록·실거주 및 본인 명의 계약','contract',yesNo,a.contract)}${selectField('1인 가구 또는 공고가 허용하는 청년 동거가구','family',yesNo,a.family)}${selectField('공고의 중복수혜·공공임대·부모 임대인 등 제외사유 없음','exclusions',yesNo,a.exclusions)}`}</div><p class="legend">${topic==='transport'?'2026년 9월 서울 만 19~34세, 월 15~60회·20만원 이하만 계산. 시차: 05:30~06:30 / 09~10시 / 16~17시 / 19~20시.':'2026년 접수는 5월 19일 종료. 선정 가정 금액만 계산하며 현재 받을 돈으로 합산하지 않아요. 가구·소득·제외사유는 아래 공식 공고를 확인해주세요.'}</p><button class="primary">내 조건으로 계산하기</button></form><div id="guide-result" aria-live="polite"></div><a class="official-link" target="_blank" rel="noopener" href="${topic==='housing'?'https://housing.seoul.go.kr/site/main/content/sh01_060513':'https://www.shinhancard.com/pconts/html/card/micro/k_pass_micro.html'}">공식 조건 전체 보기 ↗</a>`)}
async function runGuide(e,topic){e.preventDefault();const f=new FormData(e.target);state[topic+'Answers']={};for(const [k,v]of f){if(k.startsWith('p_'))state.profile[k.slice(2)]=v;else state[topic+'Answers'][k]=v}try{const d=guest?calc.diagnose(state):await api('diagnose',{state});calcResult=d;const x=d[topic];if(topic==='transport'&&x.monthly!==null){state.rewards.bus=true;addFurniture('bus');award('compare-transport-'+month,10)}if(topic==='housing'&&x.status!=='unknown'){state.rewards.board=true;addFurniture('board')}speech=x.message;render();$('#guide-result').innerHTML=`<div class="answer-bubble"><b>${who().name} · 계산 결과</b><p>${esc(x.message)}</p></div>${(x.rows||[]).map(r=>`<div class="row"><span>${esc(r.label)}<small>${esc(r.formula)}</small></span><strong>환급 ${money(r.saving)}</strong></div>`).join('')}${(x.checks||[]).map(c=>`<div class="check-result">${c.ok===null?'○':c.ok?'✓':'!'} ${esc(c.label)} · ${c.ok===null?'미확인':c.ok?'입력 기준 충족':'기준과 불일치'}</div>`).join('')}<p class="legend">${x.assumptions.map(esc).join('<br>')}</p><form onsubmit="askAI(event,'${topic}')"><label class="field">${who().name}에게 더 물어보기<input name="question" required maxlength="1200" placeholder="왜 이 방법이 유리해? 다음에 뭘 하면 돼?"></label><label class="check"><input name="ai" type="checkbox">AI 설명 사용 · 질문과 계산 조건을 OpenAI에 전송 (이메일 제외)</label><button class="secondary">${who().name}에게 질문하기</button></form><div id="ai-answer" aria-live="polite"></div>`;await flush()}catch(err){toast(err.message)}}
async function askAI(e,topic){e.preventDefault();const f=new FormData(e.target),out=$('#ai-answer');out.textContent=who().name+'가 설명을 준비하고 있어요…';try{await flush();const d=guest?{mode:'calculation',answer:calc.diagnose(state)[topic].message,notice:'샘플은 계산 안내만 제공해요. 로그인 후 API가 설정된 서버에서 AI를 이용할 수 있어요.'}:await api('chat',{topic,message:f.get('question'),useAI:f.has('ai'),character:state.character});out.textContent=(d.mode==='llm'?'AI 설명':'계산 기반 안내')+' · '+(d.notice||'')+'\n'+d.answer}catch(err){out.textContent=err.message}}
compareModal=()=>openGuide('transport');housingWorkshop=()=>openGuide('housing');
function authScreen(signup=false){let overlay=$('#auth');if(!overlay){overlay=document.createElement('div');overlay.id='auth';document.body.append(overlay)}overlay.innerHTML=`<section class="auth-card"><div class="auth-art"><span class="eyebrow">TEONG DEFENSE</span><h1>사는 곳과 가는 길,<br>우리 같이 돌보자.</h1><img src="tang.png" alt="탕이와 함께하는 생활"><p>주거·교통을 점검하면<br>작은 집과 지갑 수호자가 자라요.</p></div><div class="auth-form"><span class="tag">${signup?'새로운 동료가 되어주세요':'다시 만나서 반가워요'}</span><h2>${signup?'우리 집 입주하기':'우리 집에 로그인'}</h2><form onsubmit="authenticate(event,${signup})"><div class="fields">${field('이메일','email','','email')}<label class="field">비밀번호 (10자 이상)<input type="password" name="password" minlength="10" maxlength="128" required autocomplete="${signup?'new-password':'current-password'}"></label>${signup?`${field('별명','nickname','','text')}${field('만 나이','age')}${selectField('거주 지역','region',[['서울','서울'],['경기','경기'],['인천','인천'],['그 외 지역','그 외 지역']])}${selectField('월세 거주 여부','renting',[['월세 거주','월세 거주'],['월세 아님','월세 아님']])}${field('월세 (원)','rent')}${field('관리비 (원)','fee')}${field('월 교통비 (원)','transport')}${field('월 이용 횟수','rides')}${selectField('주요 교통수단','mode',[['버스·지하철','버스·지하철'],['광역버스·GTX','광역버스·GTX'],['택시·자가용','택시·자가용']])}${selectField('동료 선택','character',[['tang','탕이 · 남성형'],['teong','텅이 · 여성형']],'teong')}`:''}</div><p class="legend">${signup?'기본 정보는 모르면 건너뛰세요. 이메일·암호화된 비밀번호·생활정보는 계정별로 서버에 저장하며, 내 정보에서 계정을 삭제할 수 있어요. 소득·재산은 주거 상담 때만 질문해요.':'가입한 이메일과 비밀번호로 기록과 방을 불러와요.'}</p><button class="primary">${signup?'가입하고 첫 진단 시작':'로그인'}</button><p id="auth-error" role="alert"></p></form><div class="auth-links"><button onclick="authScreen(${!signup})">${signup?'이미 계정이 있어요':'처음이에요 · 회원가입'}</button><button onclick="startGuest()">샘플로 먼저 둘러보기 →</button></div></div></section>`}
function applyAccount(d){accountUser=d.user;revision=d.revision;state={...JSON.parse(JSON.stringify(initialState)),...d.state,view:'home'};state.gameRound=0;state.interaction='idle';lastSaved=snapshot();calcResult=d.diagnosis;ready=true;guest=false;$('#auth')?.remove();render()}
async function authenticate(e,signup){e.preventDefault();const f=new FormData(e.target),button=e.target.querySelector('button');button.disabled=true;try{let s=JSON.parse(JSON.stringify(initialState));if(signup){for(const k of Object.keys(s.profile))s.profile[k]=f.get(k)||'';s.profile.nickname=f.get('nickname')||'';s.character=f.get('character')||'teong';s.diagnosed=true;s.rewards.flag=true;s.equipped.push('plant');s.ledger=[{key:'diagnosis',pts:30,date:today}]}const d=await api(signup?'signup':'login',{email:f.get('email'),password:f.get('password'),...(signup?{state:s}:{})});applyAccount(d);toast(signup?'첫 진단 완료 · +30 GP! 알려준 조건으로 시작할게요.':'왔구나! 네 자리 비워뒀어.')}catch(err){$('#auth-error').textContent=err.message}finally{button.disabled=false}}
function startGuest(){state=JSON.parse(JSON.stringify(initialState));state.profile={...state.profile,nickname:'샘플 수호자',age:'23',region:'서울',renting:'월세 거주',rent:'500000',fee:'70000',transport:'80000',rides:'40',mode:'버스·지하철'};state.transportAnswers={registered:'yes',daily:'yes',fare:'low',offpeak:'0'};state.housingAnswers={birthYear:'2003',deposit:'10000000',income:'2500000',household:'1',assets:'30000000',car:'0',noHome:'yes',contract:'yes',family:'yes',exclusions:'yes'};guest=true;ready=true;accountUser=null;$('#auth')?.remove();render();toast('샘플 정보로 체험 중이에요. 회원 기록에는 저장되지 않아요.')}
async function signOut(){try{await flush();if(accountUser)await api('logout',{});accountUser=null;guest=false;ready=false;state=JSON.parse(JSON.stringify(initialState));render();authScreen()}catch(e){toast(e.message)}}
function removeAccount(){if(!accountUser)return toast('샘플은 저장된 계정이 없어요.');modal('<h2>계정과 모든 기록을 삭제할까요?</h2><p>소비·혜택·방·생활정보가 삭제되며 되돌릴 수 없어요.</p><button class="primary" onclick="confirmRemoveAccount()">모두 삭제</button>')}
async function confirmRemoveAccount(){try{clearTimeout(saveTimer);if(saveTask)await saveTask;await api('account',{},'DELETE');accountUser=null;closeModal();await signOut()}catch(e){toast(e.message)}}
window.addEventListener('beforeunload',e=>{if(accountUser&&snapshot()!==lastSaved){e.preventDefault();e.returnValue=''}});
(async()=>{try{calc=await import('./calculations.js');const d=await api('account',undefined,'GET');applyAccount(d)}catch{render();authScreen()}})();
