/* Room-first demo, session-only state. All money and progression stay separate. */
Object.assign(state,{character:'teong',roomTheme:'day',equipped:['rug'],homeChecklist:[],mementos:[],placement:'center',gameRound:0,interaction:'idle',decor:{}});
const companions={tang:{name:'탕이',label:'남성형 수호 정령',intro:'우리 집, 같이 멋지게 만들어볼까?',detail:'초록 스카프를 두른 지갑 수호자',file:'tang.png'},teong:{name:'텅이',label:'여성형 수호 정령',intro:'여기에 네가 좋아하는 것들을 채워보자!',detail:'작은 꽃을 단 지갑 수호자',file:'teong-female.png'}};
const furniture=[{id:'rug',name:'웰컴 러그',cell:2,require:'처음부터 함께하는 선물',free:true,spot:'rug'},{id:'desk',name:'기록 책상',cell:0,require:'소비 1건 직접 기록',reward:'desk',spot:'desk'},{id:'bus',name:'초록 버스 선반',cell:1,require:'교통비 비교 1회 완료',reward:'bus',spot:'bus'},{id:'board',name:'우리 집 작전 보드',cell:3,require:'주거 조건 점검 완료',reward:'board',spot:'board'},{id:'plant',name:'잘 자라는 화분',cell:4,require:'첫 고정비 진단 완료',reward:'flag',spot:'plant'},{id:'lamp',name:'포근한 스탠드',cell:5,require:'첫 주간 점검 완료',reward:'rug',spot:'lamp'}];
const original={render,saveProfile,saveRecord,finishCompare,finishReview,armor:baseArmorView,recordModal,policyModal};
function who(){return companions[state.character]}
function unlocked(f){return f.free||!!state.rewards[f.reward]}
function sprite(f,cls=''){return `<span class="furniture-sprite cell-${f.cell} ${cls}" aria-hidden="true"></span>`}
function rewardRows(){return furniture.map(f=>`<div class="reward-row ${unlocked(f)?'unlocked':''}">${sprite(f,'tiny')}<div><strong>${f.name}</strong><small>${f.require}</small></div><span>${unlocked(f)?'✓':'○'}</span></div>`).join('')}
navs.splice(0,navs.length,['home','⌂','우리 집'],['armor','⌕','생활 연구소'],['records','▤','소비 기록'],['profile','♙','내 정보']);
function room(){return `<div class="room-toolbar"><div><span class="eyebrow">OUR FIRST HOME</span><h2>${who().name}와 나의 작은 집 <span>Lv. ${Math.min(3,1+Math.floor(points()/50))}</span></h2></div><button class="secondary" onclick="chooseCompanion()"><span class="char-dot ${state.character}"></span>동료 바꾸기</button></div><section class="living-room theme-${state.roomTheme} place-${state.placement}" aria-label="가구를 누르면 상호작용할 수 있는 방"><img class="room-art" src="room.png" alt="도시가 보이는 창문과 나무 바닥이 있는 작은 방"><div class="room-atmosphere"></div><div class="room-chip">${state.roomTheme==='night'?'☾ 느긋한 밤':state.roomTheme==='sunset'?'◒ 노을 지는 오후':'☀ 햇살 좋은 우리 집'}</div><div class="room-tools"><button onclick="roomInfo()" aria-label="방 사용법">?</button></div>${furniture.filter(f=>unlocked(f)&&state.equipped.includes(f.id)).map(f=>`<button class="placed-furniture spot-${f.spot}" onclick="furnitureAction('${f.id}')" aria-label="${f.name} 사용하기">${sprite(f)}<span class="furniture-caption">${f.name} ↗</span></button>`).join('')}<div class="companion-speech" aria-live="polite"><b>${who().name}</b><span>${esc(speech.slice(0,65)).replaceAll('텅이',who().name)}</span></div><button class="mascot main-mascot companion ${state.interaction}" data-pose="${pose}" onclick="pet()" aria-label="${who().name}와 대화하기"></button><div class="room-bottom"><span>${Object.values(state.rewards).filter(Boolean).length?'우리가 한 일이 이 공간에 남아요.':'첫 가구는 선물이에요. 나머지는 생활을 점검하며 채워요.'}</span><button onclick="moveCompanion()">자리 옮기기 ⇄</button></div></section><div class="companion-controls"><button onclick="talkMenu()">☏ 대화하기</button><button onclick="playGame()">✌ 가위바위보</button><button onclick="animateCompanion('dance',2,'우리 집 입주 기념 댄스! 박자는… 마음으로 맞추자!')">♫ 같이 춤추기</button><button onclick="animateCompanion('nap',3,'잠깐 쉬어도 괜찮아. 우리 집은 어디 안 가니까.')">☾ 쉬어가기</button></div>`}
function home(){const have=furniture.filter(unlocked).length;return `${room()}<section class="decorator card"><div class="section-heading"><div><span class="eyebrow">MAKE IT OURS</span><h2>우리 집 꾸미기 <small>${have} / ${furniture.length}개 발견</small></h2></div><div class="theme-picker" aria-label="방 분위기"><button class="${state.roomTheme==='day'?'selected':''}" onclick="setTheme('day')" aria-label="낮">☀</button><button class="${state.roomTheme==='sunset'?'selected':''}" onclick="setTheme('sunset')" aria-label="노을">◒</button><button class="${state.roomTheme==='night'?'selected':''}" onclick="setTheme('night')" aria-label="밤">☾</button></div></div><div class="furniture-inventory">${furniture.map(f=>`<button class="inventory-item ${unlocked(f)?'owned':'locked'} ${state.equipped.includes(f.id)?'equipped':''}" onclick="toggleFurniture('${f.id}')">${sprite(f)}<strong>${f.name}</strong><span>${unlocked(f)?(state.equipped.includes(f.id)?'✓ 배치 중':'＋ 배치하기'):'○ 획득 방법'}</span></button>`).join('')}</div><p class="decor-hint">소품을 눌러 놓거나 보관하세요. 방 안의 가구를 누르면 ${who().name}가 사용해요.</p></section><section class="neighborhood"><div class="section-heading"><div><span class="eyebrow">BETTER HOME, BETTER COMMUTE</span><h2>우리 집 밖의 생활도, 조금 더 편하게</h2></div></div><div class="mission-grid"><button class="mission-card housing" onclick="housingWorkshop()"><span class="mission-category">01 / 주거</span><strong>텅이와 월세 이야기</strong><p>월세·관리비와 지원 조건을 함께 정리해요.</p><span class="mission-reward">${state.rewards.board?'✓ 작전 보드 획득 완료':'🎁 우리 집 작전 보드'}</span><span class="mission-arrow">↗</span></button><button class="mission-card commute" onclick="compareModal()"><span class="mission-category">02 / 교통</span><strong>내 교통비 혜택 계산</strong><p>이용 횟수와 구간을 바꾸며 비교해요.</p><span class="mission-reward">${state.rewards.bus?'✓ 버스 선반 획득 완료':'🎁 초록 버스 선반'}</span><span class="mission-arrow">↗</span></button></div></section><div class="compact-summary"><div><small>이번 달 실제 지출</small><b>${money(total())}</b></div><div><small>예상 절약액</small><b>아직 없음</b></div><div><small>확인한 혜택 · 사용자 입력</small><b>${state.benefits.length?money(state.benefits.reduce((s,b)=>s+b.amount,0)):'아직 없음'}</b></div></div><div class="home-note">${state.records.some(r=>r.sample)?'샘플 소비 기록 포함 · ':''}가구와 GP는 행동 보상이에요. 실제 돈이나 지원금으로 바뀌지 않아요.</div>`}
render=function(){original.render();document.body.dataset.character=state.character;$('.mini-mascot').style.backgroundImage=`url('${who().file}')`;$('#title').textContent={home:'오늘은 우리 집에서 뭘 해볼까?',armor:'우리의 생활 연구소',records:'작은 기록, 든든한 하루',profile:'우리의 생활을 알려주세요'}[state.view];$('#subtitle').textContent={home:'함께 놀고, 생활을 살피고, 좋아하는 공간을 채워가요.',armor:'주거와 이동을 살펴보면, 우리 집에도 변화가 생겨요.',records:'필요한 지출도 편하게. 기록 자체가 우리 집을 키워요.',profile:'모르는 항목은 건너뛰어도 괜찮아요.'}[state.view];$('.right').innerHTML=rightPanel();$('.side-note').innerHTML=`<span>작은 집에서 시작하는<br>조금 더 편한 생활.</span><p>${who().name}가 기다리고 있어요.</p><div class="mini-mascot mascot"></div>`;$('.mini-mascot').style.backgroundImage=`url('${who().file}')`;$('.profile small').textContent=who().name+'와 함께하는 중';document.querySelectorAll('.mascot').forEach(e=>e.style.backgroundImage=`url('${who().file}')`);document.querySelectorAll('.brand small').forEach(e=>e.textContent='OUR LITTLE HOME');document.querySelectorAll('.side-label').forEach(e=>e.textContent='함께 사는 작은 집')};
function rightPanel(){const p=points(),level=Math.min(3,1+Math.floor(p/50));return `<div class="date-label">오늘도, 한 걸음씩</div><section class="card companion-profile"><div class="section-title">우리 집 동료 <button onclick="chooseCompanion()">변경 ↗</button></div><div class="mascot portrait"></div><h2>${who().name} <span>${state.character==='tang'?'♂':'♀'}</span></h2><p>${who().detail}</p><div class="companion-status">${pose===3?'☾ 지금은 쉬는 중':state.interaction==='dance'?'♫ 신나는 입주 파티':'♡ 너랑 함께해서 좋은 날'}</div></section><section class="card growth"><div class="section-title">함께 쌓은 경험 <span>Lv. ${level}</span></div><h2 class="experience">${p} <small>GP</small></h2><div class="progress"><div style="width:${p>=100?100:(p%50)*2}%"></div></div><div class="progress-label"><span>${p>=100?'든든한 우리 집':`다음 단계까지 ${50-p%50} GP`}</span><span>총 3단계</span></div><p>기록을 쉬어도, 지출이 많아도<br>우리 집은 사라지지 않아요.</p></section><section class="card next-actions"><div class="section-title">집을 채우는 작은 일</div>${[['flag','첫 고정비 진단','화분 · +30 GP',"navigate('profile')"],['desk','소비 한 건 기록','책상 · 하루 +5 GP','recordModal()'],['bus','교통비 비교','버스 선반 · 월 +10 GP','compareModal()'],['board','주거 조건 점검','우리 집 작전 보드','housingWorkshop()'],['rug','이번 주 생활 점검','스탠드 · 주 +20 GP','reviewModal()']].map(([k,t,r,fn])=>`<button class="task-row" onclick="${fn}"><span class="task-check ${state.rewards[k]?'done':''}">${state.rewards[k]?'✓':'○'}</span><span><b>${t}</b><small>${r}</small></span><span>›</span></button>`).join('')}</section><button class="sample-button" onclick="loadSample()">▤ 7일 샘플로 점검 체험하기</button><p class="side-disclaimer">샘플은 실제 기록과 구분해 표시돼요.<br>샘플 불러오기에는 포인트가 없어요.</p>`}
/* Base rendering targets remain available even after the side panel is replaced. */
const coreRender=original.render;original.render=function(){if(!$('#points')){$('.right').innerHTML='<div id="today"></div><div id="level"></div><div id="points"></div><div id="next"></div><div id="bar"></div><div id="weekPoints"></div><div id="reward-count"></div><div id="rewards"></div>'}coreRender()};
function chooseCompanion(){modal(`<h2>함께 살 동료를 골라주세요</h2><p>능력과 보상은 같아요. 언제든 바꿀 수 있고 방과 기록은 그대로 남아요.</p><div class="companion-choices">${Object.entries(companions).map(([id,c])=>`<button class="character-choice ${state.character===id?'selected':''}" onclick="selectCompanion('${id}')"><span class="choice-sprite" style="background-image:url('${c.file}')"></span><strong>${c.name}</strong><small>${c.label}</small><p>${c.detail}</p><span>${state.character===id?'✓ 함께 살고 있어요':'함께 살기 →'}</span></button>`).join('')}</div>`)}
function selectCompanion(id){if(!companions[id])return;state.character=id;pose=2;speech=who().intro;state.interaction='greet';closeModal();render();toast(who().name+'와 함께 살게 되었어요. 방과 기록은 그대로예요.')}
let animationTimer;function animateCompanion(action,p,line){state.interaction=action;pose=p;speech=line;render();clearTimeout(animationTimer);if(action!=='nap')animationTimer=setTimeout(()=>{state.interaction='idle';render()},2800)}
function setTheme(theme){if(!['day','sunset','night'].includes(theme))return;state.roomTheme=theme;animateCompanion('greet',theme==='night'?3:0,theme==='night'?'불빛이 포근하다. 오늘 이야기는 여기까지 해도 좋아.':theme==='sunset'?'창밖이 노을빛이야. 오늘도 우리 집은 따뜻하네.':'햇살 좋은 날! 창가에 앉아서 뭐 할까?')}
function moveCompanion(){const places=['center','left','right'];state.placement=places[(places.indexOf(state.placement)+1)%3];animateCompanion('walk',0,'여기 앉아볼까? 생각보다 전망이 좋은데!')}
function toggleFurniture(id){const f=furniture.find(f=>f.id===id);if(!f)return;if(!unlocked(f)){modal(`<h2>${f.name}를 우리 집으로</h2><div class="furniture-preview">${sprite(f)}</div><p>${f.require}하면 받을 수 있어요. 돈을 쓰거나 정책에 선정될 필요는 없어요.</p><div class="form-actions"><button class="primary" onclick="closeModal();${{desk:'recordModal()',bus:'compareModal()',board:'housingWorkshop()',plant:"navigate('profile')",lamp:'reviewModal()'}[id]}">지금 해보기 →</button></div>`);return}state.equipped=state.equipped.includes(id)?state.equipped.filter(x=>x!==id):[...state.equipped,id];render();toast(state.equipped.includes(id)?f.name+'를 배치했어요. 방 안에서 눌러보세요!':f.name+'를 보관했어요. 언제든 다시 꺼낼 수 있어요.')}
function addFurniture(id){if(!state.equipped.includes(id))state.equipped.push(id)}
saveProfile=function(e){original.saveProfile(e);addFurniture('plant');speech='생활 정보를 알았으니 작전 시작! 화분도 한 자리 차지할게.';render()};
saveRecord=function(e,id){const before=state.records.length;original.saveRecord(e,id);if(state.records.length>before){addFurniture('desk');speech='장부 정리 끝! 책상도 생겼으니 이제 제법 우리 집 같지?';render()}};
finishCompare=function(e){original.finishCompare(e);if(state.rewards.bus){addFurniture('bus');speech='교통비 실험 끝! 이 버스는 우리 집 노선 1호야.';render()}};
finishReview=function(){original.finishReview();addFurniture('lamp');speech='이번 주 생활 점검 끝! 스탠드 켜고 같이 쉬자.';render()};
function talkMenu(){modal(`<h2>${who().name}에게 말 걸기</h2><p>오늘은 어떤 이야기 할까?</p><div class="talk-options"><button onclick="dialogue('tired')">오늘 좀 지쳤어.</button><button onclick="dialogue('home')">우리 집에 대해 이야기하자.</button><button onclick="dialogue('commute')">출퇴근 / 통학이 힘들어.</button><button onclick="dialogue('secret')">너만의 비밀 있어?</button></div>`)}
function dialogue(topic){const lines={tired:'오늘 버틴 것도 꽤 큰일이야. 할 일은 잠깐 내려놓고 나랑 러그에서 쉬자.',home:state.rewards.board?'우리 집 보드에 확인할 조건을 모아뒀어. 한 번에 다 해결하지 않아도 돼.':'집은 매달 돈이 나가니까 헷갈릴 때가 많아. 월세와 관리비부터 같이 정리해볼까?',commute:'매일 가는 길이니까 작은 차이도 쌓이겠지? 네 이동 횟수로 같이 비교해보자.',secret:'사실 내 방패… 가끔 냄비 뚜껑인 척해. 크기가 딱 좋거든.'};closeModal();animateCompanion(topic==='secret'?'wiggle':'greet',topic==='tired'?1:0,lines[topic]);if(topic==='home'||topic==='commute')toast(topic==='home'?'아래 주거 카드에서 우리 집 조건을 확인할 수 있어요.':'아래 교통 카드에서 내 교통비 혜택 계산을 해봐요.')}
function pet(){const actions=[['peek',1,'어? 찾았다! 방패 뒤에 숨으면 안 보일 줄 알았는데.'],['wiggle',2,'앗, 간지러! 한 번 더 누르면 춤출지도?'],['greet',0,'왔구나! 네 자리 비워뒀어. 오늘은 뭐부터 할까?'],['dance',2,'우리 집 입주 파티다! 이웃에게 들리지는 않겠지?']];const a=actions[state.gameRound++%actions.length];animateCompanion(...a)}
function furnitureAction(id){if(id==='desk'){animateCompanion('read',1,'장부가 제법 두꺼워졌네. 오늘 기록도 한 장 남겨볼까?');setTimeout(()=>recordModal(),550)}else if(id==='bus'){animateCompanion('drive',2,'부릉! 우리 집 1호 버스 출발합니다. 목적지는 생활 연구소!');toast('버스 선반에서 교통비 비교를 다시 열 수 있어요.');setTimeout(()=>compareModal(),1100)}else if(id==='board'){housingWorkshop()}else if(id==='rug'){animateCompanion('nap',3,'이 러그… 완전 낮잠 명당이야. 너도 잠깐 쉬어.')}else if(id==='plant'){animateCompanion('water',0,'물은 조금만. 잘 자라는 건 우리도 비슷하겠지?');toast('화분에 물을 줬어요. 매일 돌볼 의무는 없어요.')}else if(id==='lamp'){setTheme(state.roomTheme==='night'?'day':'night')}}
function playGame(){modal(`<h2>${who().name}와 가위바위보</h2><p>이기든 지든, 그냥 재미로 한 판! 포인트는 걸지 않아요.</p><div class="rps-opponent"><span class="mascot portrait" style="background-image:url('${who().file}')"></span><strong id="rps-line">준비됐어? 가위, 바위…</strong></div><div class="rps-buttons">${[['rock','✊','바위'],['paper','✋','보'],['scissors','✌','가위']].map(([v,i,t])=>`<button onclick="rps('${v}')">${i}<small>${t}</small></button>`).join('')}</div><div id="rps-result" aria-live="polite"></div>`)}
function rps(player){const vals=['rock','paper','scissors'];if(!vals.includes(player))return;const opponent=vals[Math.floor(Math.random()*3)],icons={rock:'✊',paper:'✋',scissors:'✌'},win={rock:'scissors',paper:'rock',scissors:'paper'};const message=player===opponent?'비겼다! 우리 좀 통하는데?':win[player]===opponent?'네가 이겼어! 다음엔 내 방패도 참가시켜야겠는걸.':'이번엔 내가 이겼다! 한 판 더 할래?';$('#rps-line').textContent=who().name+'의 선택 '+icons[opponent];$('#rps-result').innerHTML=`<p>나 ${icons[player]} : ${icons[opponent]} ${who().name}</p><strong>${message}</strong>`;speech=message;pose=2}
function housingWorkshop(){const p=state.profile;modal(`<span class="tag">주거 연구 · 내 방의 출발점</span><h2 style="margin-top:12px">우리 집 조건 점검</h2><p>월세와 관리비를 정리하고, 정책에 필요한 조건을 확인해요.</p><div class="housing-total"><span>입력한 월 주거 고정비</span><strong>${p.rent!==''&&p.fee!==''?money(Number(p.rent)+Number(p.fee)):'아직 모르는 항목이 있어요'}</strong><small>월세 ${p.rent!==''?money(+p.rent):'미입력'} + 관리비 ${p.fee!==''?money(+p.fee):'미입력'} · 실제 지출과 별도</small></div><form onsubmit="finishHousing(event)"><div class="fields"><label class="field">거주 지역<select name="region" required><option value="">선택해주세요</option>${['서울','경기','인천','그 외 지역','아직 모르겠어요'].map(x=>`<option ${p.region===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field">월세 거주 여부<select name="renting" required><option value="">선택해주세요</option>${['월세 거주','월세 아님','아직 모르겠어요'].map(x=>`<option ${p.renting===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field">소득·가구 조건<select name="income"><option>아직 확인하지 못했어요</option><option>확인할 서류를 알아봤어요</option><option>공식 조건과 비교해봤어요</option></select></label><label class="field">보증금·재산 조건<select name="deposit"><option>아직 확인하지 못했어요</option><option>확인할 서류를 알아봤어요</option><option>공식 조건과 비교해봤어요</option></select></label></div><div class="notice">모르는 조건을 알아두는 것도 점검이에요. 자격 판정이나 지원금 수령으로 처리하지 않아요. 소득·재산의 실제 금액은 수집하지 않아요.</div><label class="check"><input required type="checkbox">추가 조건과 모집 기간을 공식 안내에서 확인해야 한다는 점을 이해했어요.</label><div class="form-actions"><button type="button" class="secondary" onclick="closeModal();navigate('profile')">고정비 수정</button><button class="primary">점검 결과 보기</button></div></form>`)}
function finishHousing(e){e.preventDefault();const f=new FormData(e.target);state.homeChecklist=Object.fromEntries(f);state.rewards.board=true;addFurniture('board');closeModal();speech='모르는 조건까지 정리 끝! 우리 집 보드에 붙여둘게.';pose=2;render();const s=state.homeChecklist;modal(`<h2>우리 집 작전 보드를 받았어요!</h2><div class="furniture-preview">${sprite(furniture.find(x=>x.id==='board'))}</div><div class="notice">${s.region==='서울'&&s.renting==='월세 거주'?'서울시 청년월세지원은 확인해볼 후보예요. 연령·소득·재산·중복 지원·모집 기간은 추가 확인이 필요해요.':s.region==='아직 모르겠어요'||s.renting==='아직 모르겠어요'?'거주 지역과 월세 여부를 확인한 뒤 정책 후보를 살펴봐요.':'현재 데모의 월세 정책 후보는 서울 월세 거주자를 대상으로 해요. 입력 조건에는 후보 추천을 보류해요.'}</div><p>소득·가구: ${esc(s.income)}<br>보증금·재산: ${esc(s.deposit)}</p><div class="form-actions"><button class="secondary" onclick="closeModal();navigate('armor')">공식 정책 살펴보기</button><button class="primary" onclick="closeModal();navigate('home')">방에서 보드 보기</button></div>`)}
function armor(){return `<section class="lab-intro"><span class="eyebrow">LIVING LAB</span><h2>사는 곳과 다니는 길,<br>우리 생활의 두 가지 바탕.</h2><p>조건을 알아보는 과정이 우리 집을 채우는 경험이 돼요.</p></section><div class="mission-grid" style="margin-bottom:20px"><button class="mission-card housing" onclick="housingWorkshop()"><span class="mission-category">주거 실험</span><strong>우리 집 조건 정리</strong><span class="mission-reward">작전 보드 받기 →</span></button><button class="mission-card commute" onclick="compareModal()"><span class="mission-category">교통 실험</span><strong>한 달 이동 비용 비교</strong><span class="mission-reward">버스 선반 받기 →</span></button></div>${original.armor().replaceAll('방어구','생활 정보').replaceAll('교통비 비교 체험','나의 이동 비교').replaceAll('주간 점검에서 발견','주간 생활 점검에서 발견')}`}
function compareModal(){const p=state.profile;modal(`<span class="tag">교통 연구 · 나의 한 달 이동</span><h2 style="margin-top:12px">같은 길, 다른 선택</h2><p>횟수와 비용, 이용 구간을 바꾸며 어떤 조건이 중요한지 알아봐요.</p><form oninput="updateComparison()" onsubmit="finishCompare(event)"><div class="fields"><label class="field">월 예상 교통비 (원)<input name="cost" id="cost" type="number" min="0" max="10000000" required value="${esc(p.transport||80000)}"></label><label class="field">월 이용 횟수<input name="rides" id="rides" type="number" min="0" max="1000" required value="${esc(p.rides||40)}"></label><label class="field">이동 구간<select id="commute-region"><option value="seoul" ${p.route==='서울 내 이동'?'selected':''}>서울 내 이동</option><option value="cross" ${p.route==='서울·경기·인천 이동'?'selected':''}>수도권 경계 이동</option><option value="other">기타 / 잘 모르겠어요</option></select></label><label class="field">주요 수단<select id="commute-mode"><option value="public">버스·지하철</option><option value="express">광역버스·GTX</option><option value="private">택시·자가용</option></select></label><label class="field wide">비교해 볼 시뮬레이션<select id="plan"><option value="rate">환급형 가정 · 15회 이상 30%</option><option value="pass">정액형 가정 · 월 55,000원</option></select></label></div><div id="comparison"></div><div class="notice">실험용 가정: 환급형은 버스·지하철/광역 교통, 정액형은 서울 버스·지하철만 대상으로 설정했어요. 실제 2026년 상품 요금·노선·자격을 반영한 견적이 아니며 예상 절약액에 합산하지 않아요.</div><a href="https://main.kotsa.or.kr/portal/contents.do?menuCode=01080300" target="_blank" rel="noopener" class="official-link">K-패스 실제 조건은 공식 안내에서 ↗</a><div class="form-actions"><button class="primary" type="submit">비교 완료 · 버스 선반 받기</button></div></form>`);updateComparison()}
function transportEligibility(region,mode,plan){if(mode==='private')return '택시·자가용은 이 실험의 적용 대상이 아니에요.';if(region==='other')return '이용 구간을 확인해야 비용을 비교할 수 있어요.';if(plan==='pass'&&(region!=='seoul'||mode!=='public'))return '이 정액형 가정은 서울 내 버스·지하철 이동만 비교해요.';return null}
function updateComparison(){const reason=transportEligibility($('#commute-region').value,$('#commute-mode').value,$('#plan').value),x=calculate(Number($('#cost').value),Number($('#rides').value),$('#plan').value);if(reason){$('#comparison').innerHTML=`<div class="notice"><b>비교 보류</b><br>${reason} 결과를 만들지 않고, 공식 조건 확인을 다음 행동으로 남겨요.</div>`;return}$('#comparison').innerHTML=x?`<div class="comparison"><div>현재 예상 비용<strong>${money(x.cost)}</strong></div><div>실험 조건 적용 후<strong>${money(x.after)}</strong></div></div><div class="comparison-result">${x.difference>0?'가정 안에서 월 '+money(x.difference)+' 차이':x.difference<0?'현재 방식이 월 '+money(-x.difference)+' 더 저렴해요':'가정 안에서는 비용이 같아요'}</div><p class="legend">${$('#plan').value==='rate'?'월 15회 이상: 입력 교통비 × 70%. 15회 미만: 입력 교통비 그대로.':'입력 교통비와 55,000원 비교.'} 서로 대체하는 선택지는 중복 합산하지 않아요.</p>`:'금액과 횟수를 확인해주세요.'}
function roomInfo(){modal(`<h2>우리 집에서 할 수 있는 일</h2><p>탕이·텅이와 이야기하고, 가위바위보하고, 춤추거나 쉬어보세요. 방 안의 가구마다 다른 반응이 있어요.</p><div class="notice">가구를 얻은 뒤 보관함에서 배치/보관할 수 있어요.<br>낮·노을·밤 분위기와 동료의 위치도 바꿀 수 있어요.<br>가구 위치는 정해져 있고 자유 드래그는 없어요.</div>${rewardRows()}<p>성장 포인트는 기록·진단·비교·점검으로만 얻어요. 놀기·물 주기는 의무도, 점수 경쟁도 아니에요.</p>`)}
speech=who().intro;render();
